services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-net
    depends_on:
      - backend

networks:
  app-net: